#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fsearch
Version  : 0.1.3
Release  : 3
URL      : https://github.com/cboxdoerfer/fsearch/archive/0.1.3/fsearch-0.1.3.tar.gz
Source0  : https://github.com/cboxdoerfer/fsearch/archive/0.1.3/fsearch-0.1.3.tar.gz
Summary  : A fast file search utility for Unix-like systems based on GTK+3
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: fsearch-bin = %{version}-%{release}
Requires: fsearch-data = %{version}-%{release}
Requires: fsearch-license = %{version}-%{release}
Requires: fsearch-locales = %{version}-%{release}
Requires: fsearch-man = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : autoconf-archive-dev
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libpcre)

%description
FSearch is a fast file search utility, inspired by Everything Search Engine. It's written in C and based on GTK 3.

%package bin
Summary: bin components for the fsearch package.
Group: Binaries
Requires: fsearch-data = %{version}-%{release}
Requires: fsearch-license = %{version}-%{release}

%description bin
bin components for the fsearch package.


%package data
Summary: data components for the fsearch package.
Group: Data

%description data
data components for the fsearch package.


%package license
Summary: license components for the fsearch package.
Group: Default

%description license
license components for the fsearch package.


%package locales
Summary: locales components for the fsearch package.
Group: Default

%description locales
locales components for the fsearch package.


%package man
Summary: man components for the fsearch package.
Group: Default

%description man
man components for the fsearch package.


%prep
%setup -q -n fsearch-0.1.3
cd %{_builddir}/fsearch-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656454669
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/fsearch
cp %{_builddir}/fsearch-0.1.3/License %{buildroot}/usr/share/package-licenses/fsearch/179ed4834368188595c686f81ba1ba6ab8dd0a19
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang fsearch

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsearch

%files data
%defattr(-,root,root,-)
/usr/share/applications/io.github.cboxdoerfer.FSearch.desktop
/usr/share/icons/hicolor/scalable/apps/io.github.cboxdoerfer.FSearch.svg
/usr/share/metainfo/io.github.cboxdoerfer.FSearch.appdata.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fsearch/179ed4834368188595c686f81ba1ba6ab8dd0a19

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fsearch.1

%files locales -f fsearch.lang
%defattr(-,root,root,-)

